### ISSUE TITLE
Installation of openfpm_pdata, missing config.h

### ISSUE THREAD

**Issue by tomashalada** [mosaic-group/openfpm#4]
During the installation (`make install`), there is problem with config.h for pdata

```
CMake Error at openfpm_pdata/src/cmake_install.cmake:172 (file):
  file INSTALL cannot find
  "openfpm/openfpm_pdata/src/config/config.h": No such file or directory.
```

I assume this should ask for `build/config/config.h` where the `config.h` is actually located. (Manual copy solved the problem. Maybe I just messed up something in the installation procedure.)

[Related lines ](https://github.com/mosaic-group/openfpm_pdata/blob/ab66ca956af17fe9f75898658c087fe6b83cf599/src/CMakeLists.txt#L399
) in `openfpm_pdata/src/CMakeLists.txt`, probably related to #3 .

**Comment by abhinavsns** [comment]
Fixed in a394f50111ef074a4983dfb93417a584c375dc77. Thanks!
